# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import music_pb2 as music__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in music_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MusicServiceStub(object):
    """==========================
    SERVIÇO
    ==========================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListUsers = channel.unary_unary(
                '/music.MusicService/ListUsers',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=music__pb2.UserList.FromString,
                _registered_method=True)
        self.ListTracks = channel.unary_unary(
                '/music.MusicService/ListTracks',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=music__pb2.TrackList.FromString,
                _registered_method=True)
        self.PlaylistsOfUser = channel.unary_unary(
                '/music.MusicService/PlaylistsOfUser',
                request_serializer=music__pb2.UserId.SerializeToString,
                response_deserializer=music__pb2.PlaylistList.FromString,
                _registered_method=True)
        self.TracksOfPlaylist = channel.unary_unary(
                '/music.MusicService/TracksOfPlaylist',
                request_serializer=music__pb2.PlaylistId.SerializeToString,
                response_deserializer=music__pb2.TrackList.FromString,
                _registered_method=True)
        self.PlaylistsContainingTrack = channel.unary_unary(
                '/music.MusicService/PlaylistsContainingTrack',
                request_serializer=music__pb2.TrackId.SerializeToString,
                response_deserializer=music__pb2.PlaylistList.FromString,
                _registered_method=True)
        self.TrackInfo = channel.unary_unary(
                '/music.MusicService/TrackInfo',
                request_serializer=music__pb2.TrackId.SerializeToString,
                response_deserializer=music__pb2.Track.FromString,
                _registered_method=True)


class MusicServiceServicer(object):
    """==========================
    SERVIÇO
    ==========================

    """

    def ListUsers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTracks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PlaylistsOfUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TracksOfPlaylist(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PlaylistsContainingTrack(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TrackInfo(self, request, context):
        """Substitui o endpoint de streaming de áudio
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MusicServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListUsers,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=music__pb2.UserList.SerializeToString,
            ),
            'ListTracks': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTracks,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=music__pb2.TrackList.SerializeToString,
            ),
            'PlaylistsOfUser': grpc.unary_unary_rpc_method_handler(
                    servicer.PlaylistsOfUser,
                    request_deserializer=music__pb2.UserId.FromString,
                    response_serializer=music__pb2.PlaylistList.SerializeToString,
            ),
            'TracksOfPlaylist': grpc.unary_unary_rpc_method_handler(
                    servicer.TracksOfPlaylist,
                    request_deserializer=music__pb2.PlaylistId.FromString,
                    response_serializer=music__pb2.TrackList.SerializeToString,
            ),
            'PlaylistsContainingTrack': grpc.unary_unary_rpc_method_handler(
                    servicer.PlaylistsContainingTrack,
                    request_deserializer=music__pb2.TrackId.FromString,
                    response_serializer=music__pb2.PlaylistList.SerializeToString,
            ),
            'TrackInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.TrackInfo,
                    request_deserializer=music__pb2.TrackId.FromString,
                    response_serializer=music__pb2.Track.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'music.MusicService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('music.MusicService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MusicService(object):
    """==========================
    SERVIÇO
    ==========================

    """

    @staticmethod
    def ListUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/music.MusicService/ListUsers',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            music__pb2.UserList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTracks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/music.MusicService/ListTracks',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            music__pb2.TrackList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PlaylistsOfUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/music.MusicService/PlaylistsOfUser',
            music__pb2.UserId.SerializeToString,
            music__pb2.PlaylistList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TracksOfPlaylist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/music.MusicService/TracksOfPlaylist',
            music__pb2.PlaylistId.SerializeToString,
            music__pb2.TrackList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PlaylistsContainingTrack(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/music.MusicService/PlaylistsContainingTrack',
            music__pb2.TrackId.SerializeToString,
            music__pb2.PlaylistList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TrackInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/music.MusicService/TrackInfo',
            music__pb2.TrackId.SerializeToString,
            music__pb2.Track.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
