# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: music.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'music.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bmusic.proto\x12\x05music\x1a\x1bgoogle/protobuf/empty.proto\"D\n\x04User\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x11\n\tfull_name\x18\x03 \x01(\t\x12\x0b\n\x03\x61ge\x18\x04 \x01(\x05\"E\n\x05Track\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06\x61rtist\x18\x03 \x01(\t\x12\x11\n\tfile_path\x18\x04 \x01(\t\"6\n\x08Playlist\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08owner_id\x18\x03 \x01(\x05\"\x14\n\x06UserId\x12\n\n\x02id\x18\x01 \x01(\x05\"\x18\n\nPlaylistId\x12\n\n\x02id\x18\x01 \x01(\x05\"\x15\n\x07TrackId\x12\n\n\x02id\x18\x01 \x01(\x05\"&\n\x08UserList\x12\x1a\n\x05users\x18\x01 \x03(\x0b\x32\x0b.music.User\")\n\tTrackList\x12\x1c\n\x06tracks\x18\x01 \x03(\x0b\x32\x0c.music.Track\"2\n\x0cPlaylistList\x12\"\n\tplaylists\x18\x01 \x03(\x0b\x32\x0f.music.Playlist2\xd8\x02\n\x0cMusicService\x12\x34\n\tListUsers\x12\x16.google.protobuf.Empty\x1a\x0f.music.UserList\x12\x36\n\nListTracks\x12\x16.google.protobuf.Empty\x1a\x10.music.TrackList\x12\x35\n\x0fPlaylistsOfUser\x12\r.music.UserId\x1a\x13.music.PlaylistList\x12\x37\n\x10TracksOfPlaylist\x12\x11.music.PlaylistId\x1a\x10.music.TrackList\x12?\n\x18PlaylistsContainingTrack\x12\x0e.music.TrackId\x1a\x13.music.PlaylistList\x12)\n\tTrackInfo\x12\x0e.music.TrackId\x1a\x0c.music.Trackb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'music_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USER']._serialized_start=51
  _globals['_USER']._serialized_end=119
  _globals['_TRACK']._serialized_start=121
  _globals['_TRACK']._serialized_end=190
  _globals['_PLAYLIST']._serialized_start=192
  _globals['_PLAYLIST']._serialized_end=246
  _globals['_USERID']._serialized_start=248
  _globals['_USERID']._serialized_end=268
  _globals['_PLAYLISTID']._serialized_start=270
  _globals['_PLAYLISTID']._serialized_end=294
  _globals['_TRACKID']._serialized_start=296
  _globals['_TRACKID']._serialized_end=317
  _globals['_USERLIST']._serialized_start=319
  _globals['_USERLIST']._serialized_end=357
  _globals['_TRACKLIST']._serialized_start=359
  _globals['_TRACKLIST']._serialized_end=400
  _globals['_PLAYLISTLIST']._serialized_start=402
  _globals['_PLAYLISTLIST']._serialized_end=452
  _globals['_MUSICSERVICE']._serialized_start=455
  _globals['_MUSICSERVICE']._serialized_end=799
# @@protoc_insertion_point(module_scope)
