# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: streaming.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'streaming.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fstreaming.proto\x12\x05music\"D\n\x04User\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x11\n\tfull_name\x18\x03 \x01(\t\x12\x0b\n\x03\x61ge\x18\x04 \x01(\x05\"W\n\x05Track\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06\x61rtist\x18\x03 \x01(\t\x12\x11\n\tfile_path\x18\x04 \x01(\t\x12\x10\n\x08\x64uration\x18\x05 \x01(\x05\"^\n\x08Playlist\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x1a\n\x05owner\x18\x03 \x01(\x0b\x32\x0b.music.User\x12\x1c\n\x06tracks\x18\x04 \x03(\x0b\x32\x0c.music.Track\"\x0e\n\x0c\x45mptyRequest\" \n\rUserIdRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\"(\n\x11PlaylistIdRequest\x12\x13\n\x0bplaylist_id\x18\x01 \x01(\x05\"\"\n\x0eTrackIdRequest\x12\x10\n\x08track_id\x18\x01 \x01(\x05\"+\n\rUsersResponse\x12\x1a\n\x05users\x18\x01 \x03(\x0b\x32\x0b.music.User\".\n\x0eTracksResponse\x12\x1c\n\x06tracks\x18\x01 \x03(\x0b\x32\x0c.music.Track\"7\n\x11PlaylistsResponse\x12\"\n\tplaylists\x18\x01 \x03(\x0b\x32\x0f.music.Playlist\",\n\rTrackResponse\x12\x1b\n\x05track\x18\x01 \x01(\x0b\x32\x0c.music.Track2\x8d\x03\n\x0cMusicService\x12\x35\n\x08GetUsers\x12\x13.music.EmptyRequest\x1a\x14.music.UsersResponse\x12\x37\n\tGetTracks\x12\x13.music.EmptyRequest\x1a\x15.music.TracksResponse\x12\x41\n\x0fPlaylistsOfUser\x12\x14.music.UserIdRequest\x1a\x18.music.PlaylistsResponse\x12\x43\n\x10TracksOfPlaylist\x12\x18.music.PlaylistIdRequest\x1a\x15.music.TracksResponse\x12K\n\x18PlaylistsContainingTrack\x12\x15.music.TrackIdRequest\x1a\x18.music.PlaylistsResponse\x12\x38\n\tTrackInfo\x12\x15.music.TrackIdRequest\x1a\x14.music.TrackResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'streaming_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USER']._serialized_start=26
  _globals['_USER']._serialized_end=94
  _globals['_TRACK']._serialized_start=96
  _globals['_TRACK']._serialized_end=183
  _globals['_PLAYLIST']._serialized_start=185
  _globals['_PLAYLIST']._serialized_end=279
  _globals['_EMPTYREQUEST']._serialized_start=281
  _globals['_EMPTYREQUEST']._serialized_end=295
  _globals['_USERIDREQUEST']._serialized_start=297
  _globals['_USERIDREQUEST']._serialized_end=329
  _globals['_PLAYLISTIDREQUEST']._serialized_start=331
  _globals['_PLAYLISTIDREQUEST']._serialized_end=371
  _globals['_TRACKIDREQUEST']._serialized_start=373
  _globals['_TRACKIDREQUEST']._serialized_end=407
  _globals['_USERSRESPONSE']._serialized_start=409
  _globals['_USERSRESPONSE']._serialized_end=452
  _globals['_TRACKSRESPONSE']._serialized_start=454
  _globals['_TRACKSRESPONSE']._serialized_end=500
  _globals['_PLAYLISTSRESPONSE']._serialized_start=502
  _globals['_PLAYLISTSRESPONSE']._serialized_end=557
  _globals['_TRACKRESPONSE']._serialized_start=559
  _globals['_TRACKRESPONSE']._serialized_end=603
  _globals['_MUSICSERVICE']._serialized_start=606
  _globals['_MUSICSERVICE']._serialized_end=1003
# @@protoc_insertion_point(module_scope)
