# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import streaming_pb2 as streaming__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in streaming_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MusicServiceStub(object):
    """================================
    SERVIÇO
    ================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetUsers = channel.unary_unary(
                '/music.MusicService/GetUsers',
                request_serializer=streaming__pb2.EmptyRequest.SerializeToString,
                response_deserializer=streaming__pb2.UsersResponse.FromString,
                _registered_method=True)
        self.GetTracks = channel.unary_unary(
                '/music.MusicService/GetTracks',
                request_serializer=streaming__pb2.EmptyRequest.SerializeToString,
                response_deserializer=streaming__pb2.TracksResponse.FromString,
                _registered_method=True)
        self.PlaylistsOfUser = channel.unary_unary(
                '/music.MusicService/PlaylistsOfUser',
                request_serializer=streaming__pb2.UserIdRequest.SerializeToString,
                response_deserializer=streaming__pb2.PlaylistsResponse.FromString,
                _registered_method=True)
        self.TracksOfPlaylist = channel.unary_unary(
                '/music.MusicService/TracksOfPlaylist',
                request_serializer=streaming__pb2.PlaylistIdRequest.SerializeToString,
                response_deserializer=streaming__pb2.TracksResponse.FromString,
                _registered_method=True)
        self.PlaylistsContainingTrack = channel.unary_unary(
                '/music.MusicService/PlaylistsContainingTrack',
                request_serializer=streaming__pb2.TrackIdRequest.SerializeToString,
                response_deserializer=streaming__pb2.PlaylistsResponse.FromString,
                _registered_method=True)
        self.TrackInfo = channel.unary_unary(
                '/music.MusicService/TrackInfo',
                request_serializer=streaming__pb2.TrackIdRequest.SerializeToString,
                response_deserializer=streaming__pb2.TrackResponse.FromString,
                _registered_method=True)


class MusicServiceServicer(object):
    """================================
    SERVIÇO
    ================================

    """

    def GetUsers(self, request, context):
        """GET /users
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTracks(self, request, context):
        """GET /tracks
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PlaylistsOfUser(self, request, context):
        """GET /users/{id}/playlists
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TracksOfPlaylist(self, request, context):
        """GET /playlists/{id}/tracks
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PlaylistsContainingTrack(self, request, context):
        """GET /tracks/{id}/playlists
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TrackInfo(self, request, context):
        """GET /stream/{id}
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MusicServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUsers,
                    request_deserializer=streaming__pb2.EmptyRequest.FromString,
                    response_serializer=streaming__pb2.UsersResponse.SerializeToString,
            ),
            'GetTracks': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTracks,
                    request_deserializer=streaming__pb2.EmptyRequest.FromString,
                    response_serializer=streaming__pb2.TracksResponse.SerializeToString,
            ),
            'PlaylistsOfUser': grpc.unary_unary_rpc_method_handler(
                    servicer.PlaylistsOfUser,
                    request_deserializer=streaming__pb2.UserIdRequest.FromString,
                    response_serializer=streaming__pb2.PlaylistsResponse.SerializeToString,
            ),
            'TracksOfPlaylist': grpc.unary_unary_rpc_method_handler(
                    servicer.TracksOfPlaylist,
                    request_deserializer=streaming__pb2.PlaylistIdRequest.FromString,
                    response_serializer=streaming__pb2.TracksResponse.SerializeToString,
            ),
            'PlaylistsContainingTrack': grpc.unary_unary_rpc_method_handler(
                    servicer.PlaylistsContainingTrack,
                    request_deserializer=streaming__pb2.TrackIdRequest.FromString,
                    response_serializer=streaming__pb2.PlaylistsResponse.SerializeToString,
            ),
            'TrackInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.TrackInfo,
                    request_deserializer=streaming__pb2.TrackIdRequest.FromString,
                    response_serializer=streaming__pb2.TrackResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'music.MusicService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('music.MusicService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MusicService(object):
    """================================
    SERVIÇO
    ================================

    """

    @staticmethod
    def GetUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/music.MusicService/GetUsers',
            streaming__pb2.EmptyRequest.SerializeToString,
            streaming__pb2.UsersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTracks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/music.MusicService/GetTracks',
            streaming__pb2.EmptyRequest.SerializeToString,
            streaming__pb2.TracksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PlaylistsOfUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/music.MusicService/PlaylistsOfUser',
            streaming__pb2.UserIdRequest.SerializeToString,
            streaming__pb2.PlaylistsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TracksOfPlaylist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/music.MusicService/TracksOfPlaylist',
            streaming__pb2.PlaylistIdRequest.SerializeToString,
            streaming__pb2.TracksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PlaylistsContainingTrack(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/music.MusicService/PlaylistsContainingTrack',
            streaming__pb2.TrackIdRequest.SerializeToString,
            streaming__pb2.PlaylistsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TrackInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/music.MusicService/TrackInfo',
            streaming__pb2.TrackIdRequest.SerializeToString,
            streaming__pb2.TrackResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
